# vim:ft=kitty

font_size 12.0

tab_bar_style powerline

map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map cmd+left neighboring_window left
map cmd+right neighboring_window right
map cmd+up neighboring_window up
map cmd+down neighboring_window down

# map kitty_mod+h launch --location=hsplit
# map kitty_mod+v launch --location=vsplit

map kitty_mod+t goto_layout tall
map kitty_mod+s goto_layout splits

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
# include catppuccin-mocha-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_THEME
Gruvbox-Material
include gruvbox-material-theme.conf
# END_KITTY_THEME

symbol_map U+23FB-U+23FE 	MonoLisaCompletePatchNF
symbol_map U+2500-U+259F 	MonoLisaCompletePatchNF
symbol_map U+2630			MonoLisaCompletePatchNF
symbol_map U+2665			MonoLisaCompletePatchNF
symbol_map U+26A1			MonoLisaCompletePatchNF
symbol_map U+276C-U+2771 	MonoLisaCompletePatchNF
symbol_map U+2B58			MonoLisaCompletePatchNF
symbol_map U+E000-U+E00A 	MonoLisaCompletePatchNF
symbol_map U+E0A0-U+E0A2 	MonoLisaCompletePatchNF
symbol_map U+E0A3			MonoLisaCompletePatchNF
symbol_map U+E0B0-U+E0B3 	MonoLisaCompletePatchNF
symbol_map U+E0B4-U+E0C8 	MonoLisaCompletePatchNF
symbol_map U+E0CA			MonoLisaCompletePatchNF
symbol_map U+E0CC-U+E0D7 	MonoLisaCompletePatchNF
symbol_map U+E200-U+E2A9 	MonoLisaCompletePatchNF
symbol_map U+E300-U+E3E3 	MonoLisaCompletePatchNF
symbol_map U+E5FA-U+E6B7 	MonoLisaCompletePatchNF
symbol_map U+E700-U+E8EF 	MonoLisaCompletePatchNF
symbol_map U+EA60-U+EC1E 	MonoLisaCompletePatchNF
symbol_map U+ED00-U+EFCE 	MonoLisaCompletePatchNF
symbol_map U+EE00-U+EE0B 	MonoLisaCompletePatchNF
symbol_map U+F000-U+F2FF 	MonoLisaCompletePatchNF
symbol_map U+F300-U+F381 	MonoLisaCompletePatchNF
symbol_map U+F400-U+F533 	MonoLisaCompletePatchNF
symbol_map U+F500-U+FD46 	MonoLisaCompletePatchNF
symbol_map U+F0001-U+F1AF0 	MonoLisaCompletePatchNF

# BEGIN_KITTY_FONTS
font_family      	family=MonoLisa 	style=Regular 	variable_name= features='+ss08 +ss03 +ss07 +ss10 +zero'
bold_font        	family=MonoLisa 	style=SemiBold 	variable_name= features='+ss08 +ss03 +ss07 +ss10 +zero'
italic_font     	family=MonoLisaItalic 	style=Regular 	variable_name= features='+ss08 +ss03 +ss07 +ss10 +zero' 
bold_italic_font	family=MonoLisaItalic 	style=SemiBold 	variable_name= features='+ss08 +ss03 +ss07 +ss10 +zero' 
# END_KITTY_FONTS

# BEGIN_KITTY_FONTS
# font_family      family='JetBrainsMonoNL Nerd Font Mono' style=SemiBold
# bold_font        family='JetBrainsMonoNL Nerd Font Mono' style=Bold
# italic_font      family='JetBrainsMonoNL Nerd Font Mono' style='SemiBold Italic'
# bold_italic_font family='JetBrainsMonoNL Nerd Font Mono' style='Bold Italic'
# END_KITTY_FONTS
