set -g prefix "C-\\"
unbind C-b

# set -g default-terminal "screen-256color"
# set -ga terminal-overrides ",xterm-256color:Tc"

set -g base-index 1
set -g renumber-windows on
setw -g pane-base-index 1

unbind r
bind r source-file "~/.config/tmux/tmux.conf"


bind-key ! break-pane -d -n stash 
bind-key @ join-pane -b -s $.1

bind C new-window -c "#{pane_current_path}"
bind C-c attach-session -c "#{pane_current_path}"

bind X kill-window

setw -g mode-keys vi

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
setw -g xterm-keys on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

set -g @gb_yellow	'#D8a657'
set -g @gb_red		'#7DAEA3'
set -g @gb_bg		'#282828'
set -g @gb_gray		'#504945'
set -g @gb_white	'#ddc7a1'

set -g status-style "bg=#{?client_prefix,#0e363e,#4f422e},fg=#ddc7a1"

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=#ddc7a1,bg=#504945"
set -g status-right-style "none"
set -g pane-active-border-style "fg=#{@gb_yellow}"
set -g message-style "fg=#ddc7a1,bg=#504945"
set -g pane-border-style "fg=#504945"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#ddc7a1,bg=#32302f"

set -g status-left "#[bg=#{?client_prefix,#{@gb_red},#{@gb_yellow}}]#[fg=#{@gb_bg}]  #S  "
set -g status-right "  #{ram_percentage} | #{cpu_percentage} #[fg=#{?client_prefix,#{@gb_red},#{@gb_yellow}}]▐#[fg=#{@gb_bg},bg=#{?client_prefix,#{@gb_red},#{@gb_yellow}},bold]   #{battery_percentage} | %H:%M "

setw -g window-status-format "#[fg=#ddc7a1,bg=#{?client_prefix,#0e363e,#4f422e}]  [#I]  #W  "
setw -g window-status-current-format "#[fg=#{@gb_bg},bg=#{?client_prefix,#{@gb_red},#{@gb_yellow}}]  [#I]  #W  "

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/'
run '~/.tmux/plugins/tpm/tpm'

